---
title: "Data Analysis"
author: "Sierra Kindley"
date: "Spring 2020"
output: html_document
---

```{r}
#Build new theme 'sierratheme', define its parameters, and set as default theme
sierratheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top", 
        plot.title = element_text(face = "bold", size = 16, 
                                  color = "black", hjust = 0.5))
theme_set(sierratheme)
```

```{r}
#Faceted plot of solar radiation by site   
Plot.SolarRad.AllSites <- 
  ggplot(SCAN.CA.1519.summaries, aes(x = date, y = solar_rad_avg, color = station_name_elev)) +
  geom_point(cex = 2) +
  facet_wrap(vars(station_name_elev), nrow = 5) + #create facets by station
  xlab(expression(paste("Date"))) +
  ylab(expression(paste("Mean Monthly Solar Radiaion (W/m"^2*")"))) +
  labs(title = "Mean Monthly Solar Radiation Across California SCAN Stations") +
  scale_x_date(date_breaks = "1 year", date_labels = c("2020", "2015", "2016", "2017", "2018", "2019")) +
  scale_color_manual(values = c("#CC9966", "#933366", "#CC6699", "#9966CC", "#CC99FF")) +
  theme(legend.position = "none") #remove legend from plot
print(Plot.SolarRad.AllSites)

#Create caption for plot
Caption.SolarRad.AllSites <- 
  ggplot() +
  theme(axis.line = element_blank(), axis.text =
          element_text(color = "black", size = 9),
          plot.title = element_text(size = 9, 
                                  color = "black")) + 
  labs(title = "Figure 1. Mean monthly solar radiation (watts/square meter) accross five Soil Climate Analysis Network (SCAN) stations in California from 2015-2019. Each of the \n five SCAN stations are located at different elevations and in various regions of California. The value listed beside each station name denotes the elevation, in feet \n above sea level, of that given site. Please note: Data was not collected at the French Gulch station from May 2016-April 2017. However, this site was included in \n this analysis, as the trends evident in the present data are valuable to understanding trends at similar elevations/sites over time.")

#Combine plot and caption into single figure
Plot.SolarRad.AllSites.withcaption <-
  cowplot::plot_grid(Plot.SolarRad.AllSites, Caption.SolarRad.AllSites, 
                     align = 'h', axis = "a", 
                     nrow = 2, rel_heights = c(.9,.1))
#Save plot
ggsave(path = "/Users/sierr/Documents/Duke University/ENVIRON-872L/Kindley_ENV872_Project/Outputs", filename = "MeanMonthlySolarRadiation_AllSites.png", width = 11, height = 9, dpi = 300)
```

```{r}
#Faceted plot of mean monthly soil moisture at depth at each site
Plot.SoilMoist.Depth <-
  SCAN.CA.1519.summaries %>%
  rownames_to_column() %>%
  gather(key = key, value = value, soil_moist_perc_A_2in:soil_moist_perc_E_40in) %>%
  mutate(rowname = factor(rowname)) %>%
  ggplot(aes(date, value, color = key)) +
  geom_point(alpha = 0.85, cex = 2) +
  facet_wrap(vars(station_name_elev), nrow = 5, ) + #create facets by station
  xlab(expression(paste("Date"))) + 
  ylab(expression(paste("Mean Monthly Soil Moisture (%)"))) + 
  labs(title = "Soil Moisture at Depth Across California SCAN Stations", color = "Soil Depth") +
  scale_color_manual(values = c("#CCFFFF", "#66CCFF", "#3399CC", "#006699", "#003366"), labels = c("2 in", "4 in", "8 in",
                                "20 in", "40 in")) +
  scale_x_date(date_breaks = "1 year", date_labels = c("2020", "2015", "2016", "2017", "2018", "2019")) 
plot(Plot.SoilMoist.Depth)

#Create caption for plot
Caption.SoilMoist.Depth <- 
  ggplot() +
  theme(axis.line = element_blank(), axis.text =
          element_text(color = "black", size = 9),
          plot.title = element_text(size = 9, 
                                  color = "black")) + 
  labs(title = "Figure 2. Mean monthly soil moisture (%) at depth (inches) accross five Soil Climate Analysis Network (SCAN) stations in California from 2015-2019. Soil \n moisture was measured at soil depths of 2in, 4in, 8in, 20in, and 40in from 2015-2019. Each of the five SCAN stations are located at different elevations and in \n various regions of California. The value listed beside each station name denotes the elevation, in feet above sea level, of that given site. Please note: Data was \n not collected at the French Gulch station from May 2016-April 2017. However, this site was included in this analysis, as the trends evident in the present data are \n valuable to understanding trends at similar elevations/sites over time.")

#Combine plot and caption into single figure
Plot.SoilMoist.Depth.withcaption <-
  cowplot::plot_grid(Plot.SoilMoist.Depth, Caption.SoilMoist.Depth, 
                     align = 'h', axis = "a", 
                     nrow = 2, rel_heights = c(.9,.1))
#Save plot
ggsave(path = "/Users/sierr/Documents/Duke University/ENVIRON-872L/Kindley_ENV872_Project/Outputs", filename = "MeanMonthlySoilMoistureAtDepth_AllSites.png", width = 11, height = 9, dpi = 300)
```

```{r}
#Faceted plot of mean monthly soil temperature at depth at each site
Plot.SoilTemp.Depth <-
  SCAN.CA.1519.summaries %>%
  rownames_to_column() %>%
  gather(key = key, value = value, soil_temp_A_2in:soil_temp_E_40in) %>%
  mutate(rowname = factor(rowname)) %>%
  ggplot(aes(date, value, color = key)) +
  geom_point(alpha = 0.85, cex = 2) +
  facet_wrap(vars(station_name_elev), nrow = 5, ) + #create facets by station
  xlab(expression(paste("Date"))) + 
  ylab(expression(paste("Mean Monthly Soil Temperature ("*~degree*F*")"))) + 
  labs(title = "Soil Temperature at Depth Across California SCAN Stations", color = "Soil Depth") +
  scale_color_manual(values = c("#CCFFFF", "#66CCFF", "#3399CC", "#006699", "#003366"), labels = c("2 in", "4 in", "8 in",
                                "20 in", "40 in")) +
  scale_x_date(date_breaks = "1 year", date_labels = c("2020", "2015", "2016", "2017", "2018", "2019")) 
plot(Plot.SoilTemp.Depth)

#Create caption for plot
Caption.SoilTemp.Depth <- 
  ggplot() +
  theme(axis.line = element_blank(), axis.text =
          element_text(color = "black", size = 9),
          plot.title = element_text(size = 9, 
                                  color = "black")) + 
  labs(title = "Figure 3. Mean monthly soil temperature (degrees Fahrenheit) at depth (inches) accross five Soil Climate Analysis Network (SCAN) stations in California from \n 2015-2019. Soil temperature was measured at soil depths of 2in, 4in, 8in, 20in, and 40in from 2015-2019. Each of the five SCAN stations are located at different \n elevations and in various regions of California. The value listed beside each station name denotes the elevation, in feet above sea level, of that given site. \n Please note: Data was not collected at the French Gulch station from May 2016-April 2017. However, this site was included in this analysis, as the trends evident \n in the present data are valuable to understanding trends at similar elevations/sites over time.")

#Combine plot and caption into single figure
Plot.SoilTemp.Depth.withcaption <-
  cowplot::plot_grid(Plot.SoilTemp.Depth, Caption.SoilTemp.Depth, 
                     align = 'h', axis = "a", 
                     nrow = 2, rel_heights = c(.9,.1))
#Save plot
ggsave(path = "/Users/sierr/Documents/Duke University/ENVIRON-872L/Kindley_ENV872_Project/Outputs", filename = "MeanMonthlySoilTemperatureAtDepth_AllSites.png", width = 11, height = 9, dpi = 300)
```

```{r}
#Faceted plot of mean monthly soil moisture by solar radiation at each site
Plot.SoilMoist.SolarRad <-
  SCAN.CA.1519.summaries %>%
  rownames_to_column() %>%
  gather(key = key, value = value, soil_moist_perc_A_2in:soil_moist_perc_E_40in) %>%
  mutate(rowname = factor(rowname)) %>%
  ggplot(aes(solar_rad_avg, value, color = key)) +
  geom_point(alpha = 0.85, cex = 2) +
  facet_wrap(vars(station_name_elev), nrow = 5, ) + #create facets by station
  xlab(expression(paste("Mean Monthly Solar Radiaion (W/m"^2*")"))) + 
  ylab(expression(paste("Mean Monthly Soil Moisture (%)"))) + 
  labs(title = "Soil Moisture by Solar Radiation Across California SCAN Stations", color = "Soil Depth") +
  scale_color_manual(values = c("#CCFFFF", "#66CCFF", "#3399CC", "#006699", "#003366"), labels = c("2 in", "4 in", "8 in",
                                "20 in", "40 in"))
plot(Plot.SoilMoist.SolarRad)

#Create caption for plot
Caption.SoilMoist.SolarRad <- 
  ggplot() +
  theme(axis.line = element_blank(), axis.text =
          element_text(color = "black", size = 9),
          plot.title = element_text(size = 9, 
                                  color = "black")) + 
  labs(title = "Figure 4. Mean monthly soil moisture (%) by mean monthly solar radiation (watts/square meter) accross five Soil Climate Analysis Network (SCAN) stations in \n California from 2015-2019. Soil moisture was measured at soil depths of 2in, 4in, 8in, 20in, and 40in from 2015-2019. Each of the five SCAN stations are located \n at different elevations and in various regions of California. The value listed beside each station name denotes the elevation, in feet above sea level, of that \n given site. Please note: Data was not collected at the French Gulch station from May 2016-April 2017. However, this site was included in this analysis, as the \n trends evident in the present data are valuable to understanding trends at similar elevations/sites over time.")

#Combine plot and caption into single figure
Plot.SoilMoist.SolarRad.withcaption <-
  cowplot::plot_grid(Plot.SoilMoist.SolarRad, Caption.SoilMoist.SolarRad,
                     align = 'h', axis = "a", 
                     nrow = 2, rel_heights = c(.9,.1))
#Save plot
ggsave(path = "/Users/sierr/Documents/Duke University/ENVIRON-872L/Kindley_ENV872_Project/Outputs", filename = "MeanMonthlySoilMoistureBySolarRadiation_AllSites.png", width = 11, height = 9, dpi = 300)
```

```{r}
#Faceted plot of mean monthly soil temperature by solar radiation at each site
Plot.SoilTemp.SolarRad <-
  SCAN.CA.1519.summaries %>%
  rownames_to_column() %>%
  gather(key = key, value = value, soil_temp_A_2in:soil_temp_E_40in) %>%
  mutate(rowname = factor(rowname)) %>%
  ggplot(aes(solar_rad_avg, value, color = key)) +
  geom_point(alpha = 0.85, cex = 2) +
  facet_wrap(vars(station_name_elev), nrow = 5, ) + #create facets by station
  xlab(expression(paste("Mean Monthly Solar Radiaion (W/m"^2*")"))) + 
  ylab(expression(paste("Mean Monthly Soil Temperature ("*~degree*F*")"))) +
  labs(title = "Soil Temperature by Solar Radiation Across California SCAN Stations", color = "Soil Depth") +
  scale_color_manual(values = c("#CCFFFF", "#66CCFF", "#3399CC", "#006699", "#003366"), labels = c("2 in", "4 in", "8 in",
                                "20 in", "40 in"))
plot(Plot.SoilTemp.SolarRad)

#Create caption for plot
Caption.SoilTemp.SolarRad <- 
  ggplot() +
  theme(axis.line = element_blank(), axis.text =
          element_text(color = "black", size = 9),
          plot.title = element_text(size = 9, 
                                  color = "black")) + 
  labs(title = "Figure 5. Mean monthly soil temperature (degrees Fahrenheit) by mean monthly solar radiation (watts/square meter) accross five Soil Climate Analysis \n Network (SCAN) stations in California from 2015-2019. Soil temperature was measured at soil depths of 2in, 4in, 8in, 20in, and 40in from 2015-2019. Each of \n the five SCAN stations are located at different elevations and in various regions of California. The value listed beside each station name denotes the \n elevation, in feet above sea level, of that given site. Please note: Data was not collected at the French Gulch station from May 2016-April 2017. However, \n this site was included in this analysis, as the trends evident in the present data are valuable to understanding trends at similar elevations/sites over time.")

#Combine plot and caption into single figure
Plot.SoilTemp.SolarRad.withcaption <-
  cowplot::plot_grid(Plot.SoilTemp.SolarRad, Caption.SoilTemp.SolarRad, 
                     align = 'h', axis = "a", 
                     nrow = 2, rel_heights = c(.9,.1))
#Save plot
ggsave(path = "/Users/sierr/Documents/Duke University/ENVIRON-872L/Kindley_ENV872_Project/Outputs", filename = "MeanMonthlySoilTemperatureBySolarRadiation_AllSites.png", width = 11, height = 9, dpi = 300)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
